const fs = require('fs');

const ex = (list) => list.map(q => ({
  question: q[0],
  answer: q[1] + '\n\n*Reference: ' + q[2] + '*'
}));

const mod1 = ex([
  // Original 10
  ["What is the difference between a Profile and a Role in Salesforce?", "A Profile controls what a user can DO (Object permissions, Field-Level Security, App access). A Role controls what records a user can SEE (Record-level access via the Role Hierarchy). Every user must have exactly one Profile, but a Role is optional.", "Salesforce Help: Profiles and Roles"],
  ["What are Organization-Wide Defaults (OWD)?", "OWD is the baseline level of access that the most restricted user should have to records they do not own. It is the foundation of the sharing model. Access can only be opened up (via Roles, Sharing Rules) from the OWD, it cannot be restricted further.", "Trailhead: Data Security > Control Access to Records"],
  ["Explain the difference between a Master-Detail and a Lookup relationship.", "In a Master-Detail relationship, the child record is tightly bound to the parent (cascade delete, inherits security, requires a parent). In a Lookup relationship, the child is independent (can exist without parent, has its own security, no cascade delete by default).", "Salesforce Help: Object Relationships Overview"],
  ["What is a Junction Object and why is it used?", "A junction object is a custom object with two Master-Detail relationships. It is used to create a Many-to-Many relationship between two other objects (e.g., Job Postings and Applicants linked by a Job Application object).", "Trailhead: Data Modeling > Create a Many-to-Many Relationship"],
  ["What are Validation Rules and when do they fire?", "Validation Rules ensure data integrity by verifying that data entered by a user meets specific criteria before the record is saved. They fire during the 'Before Save' portion of the order of execution.", "Salesforce Help: Validation Rules"],
  ["What is the difference between a Standard Object and a Custom Object?", "Standard objects are provided by Salesforce out-of-the-box (e.g., Account, Contact, Opportunity). Custom objects are created by administrators to store data specific to the organization's business needs.", "Trailhead: Data Modeling > Understand Custom & Standard Objects"],
  ["How does Field-Level Security (FLS) differ from Page Layouts?", "FLS controls visibility and editability of a field universally at the database level (API, Reports, Views). Page Layouts only control visibility on the UI. If a field is hidden via FLS, a user cannot query it via API; if hidden only on Page Layout, they can still query it.", "Salesforce Help: Field-Level Security"],
  ["What happens when a Lead is converted?", "When a Lead is converted, Salesforce takes the data from the Lead and creates a new Account, Contact, and optionally an Opportunity. Custom fields on the Lead must be explicitly mapped to custom fields on the target objects.", "Trailhead: Lead Management"],
  ["What is a Roll-up Summary field?", "A Roll-up Summary field calculates values (Count, Sum, Min, Max) from related child records in a Master-Detail relationship. It sits on the Master object.", "Salesforce Help: Roll-Up Summary Field"],
  ["What is the difference between Data Loader and the Data Import Wizard?", "Data Import Wizard handles up to 50,000 records, supports basic deduplication, and has a simple UI. Data Loader handles up to 5,000,000 records, supports all objects, requires installation, and can be scheduled via CLI.", "Trailhead: Data Management > Import Data"],
  
  // New 10
  ["What is a Record Type?", "Record Types allow you to offer different business processes, picklist values, and page layouts to different users based on their Profile. For example, a 'Support Case' vs a 'Billing Case'.", "Salesforce Help: Record Types"],
  ["Can you convert a Lookup relationship to a Master-Detail relationship?", "Yes, but only if every single existing child record has a value in the lookup field. If there are orphan records, the conversion will be blocked.", "Salesforce Help: Changing Custom Field Type"],
  ["What is a Dependent Picklist?", "A dependent picklist restricts the available values in one picklist (the dependent) based on the value selected in another field (the controlling field). Checkboxes can be controlling fields, but not dependent fields.", "Salesforce Help: Dependent Picklists"],
  ["What is the difference between a Formula field and a Roll-up Summary field?", "Formula fields calculate values using fields on the same record or parent records (moving upwards in the hierarchy). Roll-up summaries calculate aggregate values from child records (moving downwards) and require a Master-Detail relationship.", "Trailhead: Point-and-Click Developer"],
  ["What is an External ID?", "An External ID is a custom field that has the 'External ID' attribute checked. It contains unique identifiers from a system outside of Salesforce and is used to prevent duplicate records during Upsert operations via Data Loader or API.", "Salesforce Help: External ID"],
  ["What is Field History Tracking?", "It allows you to track changes to up to 20 standard or custom fields on an object. It records the date, time, user, old value, and new value in a related History list.", "Salesforce Help: Field History Tracking"],
  ["What happens to a Junction Object record if one of the Master records is deleted?", "Because it has two Master-Detail relationships, deleting either of the parent (Master) records will result in the immediate cascade deletion of the junction (child) record.", "Salesforce Help: Considerations for Relationships"],
  ["What is an App in Salesforce?", "An App is a collection of tabs that operate as a unit to provide application functionality. Switching apps just changes the navigation menu, it does not change the underlying database or security access.", "Trailhead: Platform Basics > Get Started with Salesforce"],
  ["What is a Global Picklist Value Set?", "It is a shared set of picklist values that can be reused across multiple custom picklist fields and objects. If you update the global set, all fields using it are updated.", "Salesforce Help: Global Picklist Value Sets"],
  ["What is the Recycle Bin?", "When records are deleted, they are moved to the Recycle Bin where they stay for 15 days before being permanently purged. They can be restored during this window.", "Salesforce Help: Recycle Bin"]
]);

const mod2 = ex([
  // Original 10
  ["What is the difference between a Workflow Rule and a Flow?", "Workflow Rules are legacy automation tools that can only update fields, send emails, create tasks, or send outbound messages. Flow is the modern, robust automation engine that can query data, loop through records, perform complex logic, and create any record.", "Trailhead: Automate Your Business Processes"],
  ["Explain the concept of 'Order of Execution' in Salesforce.", "When a record is saved, Salesforce executes logic in a specific order: 1. System Validation, 2. Before Triggers, 3. Custom Validation Rules, 4. After Triggers, 5. Assignment Rules, 6. Auto-Response Rules, 7. Workflow Rules, 8. Escalation Rules, 9. Roll-up Summaries. (Flows have specific slots for Before-Save and After-Save).", "Salesforce Help: Triggers and Order of Execution"],
  ["What is a Record-Triggered Flow?", "A Record-Triggered Flow runs automatically when a record is created, updated, or deleted. It replaces the need for most Apex triggers. It can run 'Before Save' (for fast field updates) or 'After Save' (for related record operations).", "Trailhead: Record-Triggered Flows"],
  ["What is a Screen Flow?", "A Screen Flow provides a guided UI experience. It can pause for user input via forms, execute logic based on that input, and then update the database. Screen Flows can be embedded in Lightning Pages, Utility Bars, or launched via Quick Actions.", "Trailhead: Screen Flows"],
  ["How do you bypass Validation Rules in an automated process?", "Validation rules cannot be natively 'turned off' for specific automations. The best practice is to add a custom checkbox field (e.g., 'Bypass_Validation__c') to the User or Profile, and add logic to the Validation Rule that checks if this flag is false before firing.", "Salesforce Developer Blog: Bypassing Validation Rules"],
  ["What is a Scheduled Flow?", "A Scheduled Flow is an auto-launched flow that starts at a specific time and frequency (daily, weekly) for a batch of records that meet specific criteria.", "Salesforce Help: Schedule-Triggered Flows"],
  ["Can a Flow perform DML operations (Insert/Update) inside a Loop?", "Technically yes, but it is a massive anti-pattern. Doing so will cause the Flow to hit SOQL/DML governor limits (e.g., Too many DML statements: 151). You must use an Assignment element in the loop to add records to a Collection, and perform one DML Update outside the loop.", "Trailhead: Flow Best Practices"],
  ["What is an Approval Process?", "An Approval Process is an automated routing of a record for approval. It defines the steps to approve, the users who must approve, and the actions that happen upon approval, rejection, or recall (such as locking the record from edits).", "Trailhead: Approval Processes"],
  ["What is a Custom Metadata Type?", "Custom Metadata Types are customizable, deployable application configuration records. Unlike Custom Settings, the records themselves are metadata, meaning they can be deployed via Change Sets or SFDX.", "Salesforce Help: Custom Metadata Types"],
  ["What is a Permission Set Group?", "A Permission Set Group bundles multiple Permission Sets together based on user roles or job functions. Users assigned to the group inherit all permissions from the bundled sets.", "Salesforce Help: Permission Set Groups"],
  
  // New 10
  ["What is the difference between a Public Group and a Queue?", "A Public Group is a collection of users used for sharing rules (granting access). A Queue is a holding area for unassigned records (like Cases or Leads) until a user accepts ownership.", "Salesforce Help: Groups and Queues"],
  ["What are Sharing Rules?", "Sharing Rules are automated exceptions to Organization-Wide Defaults (OWD). They grant lateral access to records based on record ownership or criteria (e.g., all Accounts where Industry='Tech' are shared with the Sales group).", "Trailhead: Data Security"],
  ["What is Manual Sharing?", "Manual Sharing allows the owner of a record, or someone above them in the hierarchy, to explicitly share a single record with another user or group via the 'Share' button. This is only available if OWD is Private or Public Read Only.", "Salesforce Help: Manual Sharing"],
  ["What is the difference between Before-Save and After-Save Flows?", "Before-Save flows are incredibly fast (10x faster) because they update the triggering record before it hits the database. After-Save flows run after the record is saved, allowing them to access the new ID and update related records.", "Salesforce Developer Blog: Record-Triggered Flows"],
  ["What happens if a Flow encounters an error?", "If a Flow fails (e.g., DML exception), it rolls back the entire database transaction and sends an email to the admin. You can use 'Fault Paths' to catch errors gracefully and show custom messages or log the error.", "Salesforce Help: Flow Fault Paths"],
  ["What is a Dynamic Dashboard?", "A Dynamic Dashboard displays data tailored to the logged-in user viewing it, rather than a fixed running user. This ensures users only see data they are permitted to see based on their security settings.", "Salesforce Help: Dynamic Dashboards"],
  ["What is a Custom Report Type?", "A Custom Report Type acts as a template for reports. It defines the relationships between objects (e.g., 'Accounts with or without Contacts') and specifies exactly which fields are available to the report builder.", "Trailhead: Reports & Dashboards"],
  ["What is Event Monitoring?", "Event Monitoring is a Shield feature that provides API access to detailed logs of user activity (logins, reports exported, API calls). It is primarily used for security auditing and usage tracking.", "Trailhead: Event Monitoring"],
  ["What is Identity Provider (IdP) and Service Provider (SP) in SSO?", "In Single Sign-On (SSO), the IdP verifies who the user is (e.g., Okta, Active Directory). The SP is the application the user wants to access (e.g., Salesforce). Salesforce can act as both an IdP and an SP.", "Trailhead: Identity Basics"],
  ["What is a Partial Copy Sandbox?", "A Partial Sandbox includes a copy of your production metadata and a sample of your production data (up to 10,000 records per selected object). It is used for QA and UAT testing.", "Salesforce Help: Sandbox Types"]
]);

const mod3 = ex([
  // Original 10
  ["What are Governor Limits?", "Because Salesforce operates in a multi-tenant environment, Governor Limits prevent any single tenant from monopolizing shared resources (CPU, Memory, DB connections). Examples: 100 SOQL queries per sync transaction, 150 DML statements.", "Trailhead: Apex Basics & Database"],
  ["What is bulkification?", "Bulkification is the practice of writing code that handles collections of records (Lists, Sets) rather than processing single records one at a time. This ensures the code scales properly without hitting limits when processing data imports.", "Trailhead: Bulk Apex Triggers"],
  ["Explain the difference between a Map, List, and Set in Apex.", "List: An ordered collection of elements that allows duplicates. Set: An unordered collection of unique elements (no duplicates). Map: A collection of key-value pairs where each key maps to a single value.", "Apex Developer Guide: Collections"],
  ["What is the difference between Database.insert() and the insert DML statement?", "The `insert` keyword rolls back the entire transaction if any record fails. `Database.insert(records, false)` allows partial success; it commits the valid records and returns errors for the failed ones without halting execution.", "Apex Developer Guide: Database Methods"],
  ["What is a Trigger Handler pattern?", "It is an architecture where the Apex Trigger itself contains no logic (logic-less). Instead, the trigger immediately calls a separate Handler class to execute the logic based on the trigger context (e.g., BeforeInsert, AfterUpdate).", "Salesforce Developer Blog: Apex Trigger Best Practices"],
  ["What is the difference between @future and Queueable Apex?", "@future methods are basic asynchronous fire-and-forget methods that cannot take sObjects as parameters and cannot be chained. Queueable Apex allows passing complex types (like sObjects), can be chained (one calling another), and returns a Job ID for tracking.", "Trailhead: Asynchronous Apex"],
  ["What is Batch Apex?", "Batch Apex processes massive amounts of data (up to 50 million records) by breaking the work into smaller chunks (batches of 200 records by default). The class must implement `Database.Batchable`.", "Trailhead: Batch Apex"],
  ["What does the WITH SECURITY_ENFORCED clause do?", "Added to a SOQL query, it ensures that the query will throw an exception if the user does not have Field-Level Security or Object-level read access to the requested fields/objects.", "Apex Developer Guide: Enforcing Security"],
  ["How do you test a web service callout in an Apex Test class?", "Test classes cannot make real HTTP callouts. You must create a class that implements the `HttpCalloutMock` interface and use `Test.setMock()` to return a simulated response.", "Trailhead: Apex Integration Services"],
  ["What is a Mixed DML Error?", "This error occurs when you attempt to perform DML on a Setup object (like User or Group) and a non-Setup object (like Account) within the same synchronous transaction. You must separate them by moving one operation to an asynchronous method (like @future).", "Apex Developer Guide: Mixed DML"],
  
  // New 15
  ["What is the SOQL limit in a synchronous transaction?", "You can execute a maximum of 100 SOQL queries per synchronous transaction. In an asynchronous transaction (like Batch or Queueable), the limit is 200.", "Salesforce Help: Execution Governors and Limits"],
  ["What is the DML limit in a synchronous transaction?", "You can execute a maximum of 150 DML statements (insert, update, delete) per synchronous transaction, regardless of synchronous or asynchronous context.", "Salesforce Help: Execution Governors and Limits"],
  ["What does Test.startTest() and Test.stopTest() do?", "They establish a new set of governor limits for the code enclosed within them. This ensures your test execution setup data doesn't count against the limits of the code you are actually testing. stopTest() also forces any asynchronous jobs to run synchronously.", "Apex Developer Guide: Using Limits in Tests"],
  ["What is the difference between SOQL and SOSL?", "SOQL (Salesforce Object Query Language) is used to query specific fields from a single object and its related objects. SOSL (Salesforce Object Search Language) is used for full-text searches across multiple unrelated objects simultaneously.", "Trailhead: SOQL vs SOSL"],
  ["What is Database.Stateful in Batch Apex?", "By default, instance variables in a Batch Apex class are reset between batches. If you implement Database.Stateful, the class retains its state (e.g., an error counter) across all execute methods until the finish method is called.", "Apex Developer Guide: Using Batch Apex"],
  ["What does the 'without sharing' keyword do on an Apex class?", "It enforces that the code ignores the Organization-Wide Defaults, Sharing Rules, and Manual Sharing for the running user, granting the code full access to all records in the database. (It does not bypass CRUD/FLS).", "Apex Developer Guide: Using the with sharing, without sharing"],
  ["What is System.runAs() used for?", "System.runAs() is used in test classes to execute a block of code within the context of a specific user. This is crucial for testing whether Sharing Rules and Record Visibility are functioning correctly for that profile/role.", "Apex Developer Guide: Testing Custom Controllers"],
  ["Can you call a @future method from a Batch Apex execute method?", "No. Calling a @future method from within a Batch execute method is explicitly prohibited and will throw an exception.", "Salesforce Help: Asynchronous Apex Limits"],
  ["What is the purpose of a Savepoint?", "Database.setSavepoint() allows you to mark a specific state in the database. If an error occurs later in the transaction, you can use Database.rollback(sp) to undo DML operations made after the savepoint.", "Apex Developer Guide: Transaction Control"],
  ["What is Platform Cache?", "Platform Cache is a memory layer in Salesforce used to store session or org-level data. By storing frequently accessed, static data (like complex SOQL results) in memory, you improve application performance.", "Trailhead: Platform Cache Basics"],
  ["How do you bypass governor limits?", "You cannot bypass governor limits. They are hard limits. You must redesign your code using bulkification, asynchronous processing, or caching to operate within the limits.", "Salesforce Fundamentals"],
  ["What is an Apex Exception?", "An exception is an error that disrupts the normal flow of execution, such as a NullPointerException or DmlException. They can be caught using a try-catch-finally block to handle the error gracefully.", "Apex Developer Guide: Exceptions"],
  ["What is custom metadata type used for in Apex?", "Since custom metadata records are loaded into the application cache, querying them does not count against SOQL limits. They are ideal for storing configurable variables like API keys or routing logic.", "Salesforce Developer Blog"],
  ["What happens if a SOQL query returns no records?", "If assigned to a List, the List will be empty. If assigned to a single sObject variable (e.g., Account a = [SELECT Id FROM Account LIMIT 1]), it will throw a System.QueryException: List has no rows for assignment.", "Apex Developer Guide: SOQL"],
  ["What is a Scheduled Apex class?", "It is a class that implements the Schedulable interface, allowing you to use System.schedule() to execute the code at specified times via a CRON expression.", "Apex Developer Guide: Apex Scheduler"]
]);

const mod4 = ex([
  // Original 10
  ["What is the fundamental architecture of Lightning Web Components (LWC)?", "LWC leverages native web standards (Web Components, Custom Elements, Shadow DOM, ES modules) running on the browser, rather than a custom framework abstraction like Aura. This results in lightweight, high-performance UI components.", "Trailhead: Lightning Web Components Basics"],
  ["What does the @api decorator do?", "The @api decorator exposes a public property or method, allowing a parent component to pass data down to the child component or invoke the child's method.", "LWC Developer Guide: @api"],
  ["What does the @track decorator do?", "Historically, it made primitive properties reactive. Since Spring '20, all properties are reactive by default. Now, @track is only used to tell the framework to observe deep mutations (changes to properties inside an object or array).", "LWC Developer Guide: Reactivity"],
  ["How does @wire work?", "The @wire decorator provisions data reactively from a Salesforce wire adapter or Apex method. When the parameters passed to the wire change, the wire automatically re-fetches the data and updates the component.", "LWC Developer Guide: Use the Wire Service"],
  ["What is Lightning Data Service (LDS)?", "LDS is the data caching and synchronization layer for LWC. It allows components to read, create, and modify Salesforce records without writing Apex. If two components on a page use LDS for the same record, updates to one reflect instantly in the other.", "Trailhead: Lightning Data Service"],
  ["How do child components communicate with parent components?", "Child components dispatch standard DOM CustomEvents (e.g., `this.dispatchEvent(new CustomEvent('select'))`). The parent component listens to these events via HTML attributes (e.g., `onselect={handleSelect}`).", "LWC Developer Guide: Events"],
  ["What is Shadow DOM?", "Shadow DOM is a web standard that encapsulates a component's internal DOM structure and CSS. This prevents a component's styles from bleeding out and affecting the rest of the page, and prevents external styles from bleeding in.", "LWC Developer Guide: Shadow DOM"],
  ["What is Lightning Message Service (LMS)?", "LMS is a publish-subscribe communication mechanism that allows unrelated components (siblings, LWC-to-Aura, LWC-to-Visualforce) to communicate across the entire Lightning Page using Message Channels.", "Trailhead: Lightning Message Service"],
  ["What is the difference between a wire service and imperative Apex?", "@wire is reactive and automatic; it requires the Apex method to be `cacheable=true` (read-only). Imperative Apex is invoked manually via JavaScript promises (e.g., on a button click) and is required when you need to perform DML (Insert/Update) since cacheable methods cannot perform DML.", "LWC Developer Guide: Call Apex Methods"],
  ["Explain the connectedCallback() lifecycle hook.", "connectedCallback() fires when the component is inserted into the document (DOM). It is the ideal place to perform initialization tasks like subscribing to an LMS channel or setting up component state.", "LWC Developer Guide: Lifecycle Hooks"],
  
  // New 15
  ["Explain the renderedCallback() lifecycle hook.", "renderedCallback() fires after every render of the component. You must be extremely careful not to update reactive properties inside it without a guard clause, otherwise it triggers an infinite rendering loop.", "LWC Developer Guide: Lifecycle Hooks"],
  ["Explain the disconnectedCallback() lifecycle hook.", "disconnectedCallback() fires when the component is removed from the DOM. It is used to clean up resources, such as unsubscribing from LMS channels or clearing setInterval timers to prevent memory leaks.", "LWC Developer Guide: Lifecycle Hooks"],
  ["What is the errorCallback() lifecycle hook?", "errorCallback(error, stack) acts as an error boundary. It captures errors that occur during the rendering or lifecycle hooks of any child component, allowing the parent to display an error state gracefully.", "LWC Developer Guide: Lifecycle Hooks"],
  ["Why do we need a 'key' attribute in a for:each loop?", "The key attribute assigns a unique identifier to each item in the array. This allows the LWC rendering engine to track which elements are added, removed, or reordered without re-rendering the entire list, ensuring high performance.", "LWC Developer Guide: Render Lists"],
  ["What is a slot?", "A <slot> is a placeholder inside a component that allows a parent component to inject external HTML markup into the child's Shadow DOM, enabling flexible composition.", "LWC Developer Guide: Slots"],
  ["What is Lightning Locker / LWS?", "Lightning Web Security (LWS) and Locker are security architectures that isolate components by namespace. They prevent malicious components from reading data from other components or tampering with the global DOM (preventing Cross-Site Scripting).", "LWC Developer Guide: Security"],
  ["How do you call an Apex method from LWC?", "You import the Apex method from the '@salesforce/apex/Class.Method' module. You can then invoke it either reactively using @wire or imperatively as a standard JavaScript function that returns a Promise.", "LWC Developer Guide: Call Apex Methods"],
  ["What does 'composed: true' mean in a CustomEvent?", "By default, events do not cross the Shadow DOM boundary. Setting 'composed: true' (along with 'bubbles: true') allows the event to break out of the component's Shadow DOM and propagate up to the document root.", "LWC Developer Guide: Events"],
  ["How do you import a static resource in LWC?", "You import it using the scoped module syntax: `import myResource from '@salesforce/resourceUrl/myResourceName';`.", "LWC Developer Guide: Static Resources"],
  ["How do you query elements inside an LWC?", "Because of Shadow DOM, you cannot use `document.querySelector`. You must use `this.template.querySelector('.my-class')` to access elements within the component's specific template.", "LWC Developer Guide: Query the DOM"],
  ["What is NavigationMixin?", "NavigationMixin is a module that provides methods (`this[NavigationMixin.Navigate]`) to programmatically route the user to standard Salesforce pages, records, object homes, or external URLs without hardcoding URLs.", "LWC Developer Guide: Navigate"],
  ["How do you show a toast message in LWC?", "You import `ShowToastEvent` from `lightning/platformShowToastEvent`, instantiate it with a title, message, and variant (success/error), and dispatch it using `this.dispatchEvent(new ShowToastEvent({...}))`.", "LWC Developer Guide: Toast Notifications"],
  ["How do you share JavaScript code between LWCs?", "You create a Service Component, which is an LWC containing only a `.js` file (no HTML). You export the utility functions from that file, and then import them into your other LWCs.", "LWC Developer Guide: Share Code"],
  ["What is the purpose of the js-meta.xml file?", "The metadata XML file defines the component's configuration. It specifies whether the component is `isExposed` (visible to builders), defines which targets (App Page, Record Page) it supports, and configures design attributes (properties exposed to the admin in App Builder).", "LWC Developer Guide: XML Configuration"],
  ["How do you test LWC components?", "LWC components are tested locally using the Jest testing framework (`sfdx-lwc-jest`). Tests are completely isolated from Salesforce and use mocked data to ensure the UI behaves correctly based on state changes.", "LWC Developer Guide: Testing"]
]);

const interviewQuestions = {
  '1': mod1,
  '2': mod2,
  '3': mod3,
  '4': mod4
};

const output = 'export const interviewQuestions = ' + JSON.stringify(interviewQuestions, null, 2) + ';';
fs.writeFileSync('js/data/interview-questions.js', output, 'utf8');
console.log('Successfully generated interview-questions.js with 95 questions.');
